# Generated by Django 5.2 on 2025-04-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('focus', 'Foco de Dengue'), ('case', 'Caso de Dengue em Casa')], default='focus', max_length=10, verbose_name='Tipo de Denúncia'),
        ),
    ]
