# Generated by Django 5.2 on 2025-05-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Imagem'),
        ),
    ]
