# Generated by Django 5.2 on 2025-05-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/dengue_reports/', verbose_name='Imagem'),
        ),
    ]
